--COMANDO PARA EXTRAER EL CÓDIGO DE LAS TABLAS CREADAS
SELECT DBMS_METADATA.GET_DDL('TABLE', 'CLIENTES') FROM DUAL;

--#RESULTADO
  CREATE TABLE "ECOMMERCE_OLIST"."CLIENTES" 
   (	"CUSTOMER_ID" VARCHAR2(50 BYTE), 
	"CUSTOMER_UNIQUE_ID" VARCHAR2(50 BYTE), 
	"CUSTOMER_ZIP_CODE_PREFIX" NUMBER(10,0), 
	"CUSTOMER_CITY" VARCHAR2(100 BYTE), 
	"CUSTOMER_STATE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;